/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdfgen;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Cell;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Image;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class PDForm extends javax.swing.JFrame {

    /**
     * Creates new form PDForm
     */
    public PDForm() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        lbl_formapago = new javax.swing.JLabel();
        lbl_vendedor = new javax.swing.JLabel();
        lbl_cp = new javax.swing.JLabel();
        lbl_tel = new javax.swing.JLabel();
        lbl_tipoenvio = new javax.swing.JLabel();
        lbl_cuenta = new javax.swing.JLabel();
        btn_generar = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        txt_vendedor = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_cp = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        box_formapago = new javax.swing.JComboBox<>();
        txt_tipoenvio = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_cuenta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        lbl_cantidad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_descripcion = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        lbl_precio = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_reex = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        txt_enviop = new javax.swing.JTextField();
        txt_reex = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("PDFrame"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOTAS DE VENTA");

        lbl_fecha.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_fecha.setText("Fecha:");

        lbl_nombre.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_nombre.setText("Nombre:");

        lbl_direccion.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_direccion.setText("Dirección:");

        lbl_formapago.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_formapago.setText("Forma de pago:");

        lbl_vendedor.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_vendedor.setText("Vendedor:");

        lbl_cp.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_cp.setText("Código postal:");

        lbl_tel.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_tel.setText("Tel.");

        lbl_tipoenvio.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_tipoenvio.setText("Tipo de envío:");

        lbl_cuenta.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        lbl_cuenta.setText("Cuenta:");

        btn_generar.setBackground(new java.awt.Color(255, 255, 255));
        btn_generar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_generar.setText("Imprimir");
        btn_generar.setFocusPainted(false);
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        txt_vendedor.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_nombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        txt_cp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_direccion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        box_formapago.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        box_formapago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta de crédito" }));

        txt_tipoenvio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_telefono.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        txt_cuenta.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio", "Importe"
            }
        ));
        tblDatos.setAlignmentX(2.0F);
        tblDatos.setAlignmentY(2.0F);
        jScrollPane1.setViewportView(tblDatos);

        btn_agregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        lbl_cantidad.setText("Cantidad:");

        lbl_descripcion.setText("Descripción:");

        lbl_precio.setText("Precio:");

        jLabel2.setText("ENVIO:");

        lbl_reex.setText("REEX:");

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 0, 0));
        lbl_total.setText("TOTAL");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_formapago)
                        .addGap(18, 18, 18)
                        .addComponent(box_formapago, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(lbl_cuenta)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_nombre)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_direccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_direccion)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_fecha)
                                        .addGap(18, 18, 18)
                                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_vendedor)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_vendedor))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(lbl_cp)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_tipoenvio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_tipoenvio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_tel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_cantidad)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(lbl_descripcion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_precio)
                                .addGap(18, 18, 18)
                                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_agregar)
                        .addGap(50, 50, 50)
                        .addComponent(btn_generar)
                        .addGap(376, 376, 376))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_reex)
                            .addComponent(jLabel2)
                            .addComponent(lbl_total))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_enviop, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addComponent(txt_reex))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_result)))
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_fecha)
                                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vendedor)
                                    .addComponent(txt_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nombre)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_direccion)
                                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cp)
                                    .addComponent(txt_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tel)
                                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_formapago)
                                    .addComponent(box_formapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_cuenta)
                                    .addComponent(txt_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tipoenvio)
                                    .addComponent(txt_tipoenvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_cantidad)
                                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_descripcion)
                                        .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_precio)
                                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(txt_enviop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_reex)
                            .addComponent(txt_reex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_total)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_result, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_generar)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        writePDF();
    }//GEN-LAST:event_btn_generarActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed

    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
         DefaultTableModel modelo=(DefaultTableModel) tblDatos.getModel();
         
         int cant = Integer.valueOf(txt_cantidad.getText());
         int pre = Integer.valueOf(txt_precio.getText());
            
         int importe = (cant * pre);

         Object [] fila=new Object[4];
         
         fila[0]=txt_cantidad.getText(); 
         fila[1]=txt_descripcion.getText(); 
         fila[2]=txt_precio.getText(); 
         fila[3]=importe;
         
         modelo.addRow(fila);
         tblDatos.setModel(modelo); 
         
         int enviof = Integer.valueOf(txt_enviop.getText());
         int reex = Integer.valueOf(txt_reex.getText());
            
         int total = (importe+enviof+reex);
         String total2 = String.valueOf(total);
         lbl_result.setText(total2);
          
    }//GEN-LAST:event_btn_agregarActionPerformed
    


        /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PDForm().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_formapago;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_generar;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_cp;
    private javax.swing.JLabel lbl_cuenta;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_formapago;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_reex;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JLabel lbl_tipoenvio;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_vendedor;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cp;
    private javax.swing.JTextField txt_cuenta;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_enviop;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_reex;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_tipoenvio;
    private javax.swing.JTextField txt_vendedor;
    // End of variables declaration//GEN-END:variables

    private void writePDF() {
 
        Document document = new Document();
 
        try {
        	String path = new File(".").getCanonicalPath();
        	String FILE_NAME = path + "/ticket.pdf";
        	
            PdfWriter.getInstance(document, new FileOutputStream(new File(FILE_NAME)));
 
            document.open();
 
            Paragraph paragraphHello = new Paragraph();
            paragraphHello.add("REBERZZA");
            paragraphHello.setAlignment(Element.ALIGN_JUSTIFIED);
            
            document.add(paragraphHello);
            document.add(Chunk.NEWLINE);
            document.add(Chunk.NEWLINE);
 
            Phrase line1 = new Phrase();
            Phrase line2 = new Phrase();
            Phrase line3 = new Phrase();
            Phrase line4 = new Phrase();
            Phrase line5 = new Phrase();
            Phrase line6 = new Phrase();
            Phrase line7 = new Phrase();
            Phrase line8 = new Phrase();
            
            line1.add("Nombre: "  + txt_nombre.getText());
            line2.add("Vendedor: "  + txt_vendedor.getText());
            line3.add("Dirección: "  + txt_direccion.getText());
            line4.add("C.P.: "  + txt_cp.getText());
            line5.add("Tel: "  + txt_telefono.getText());
            line3.add("Forma de Pago: "  + box_formapago.getSelectedItem());
            line4.add("Cuenta: "  + txt_cuenta.getText());
            line5.add("Tipo de envio: "  + txt_tipoenvio.getText());
 
            document.add(line1);
            document.add(Chunk.NEWLINE);
            document.add(line2);
            document.add(Chunk.NEWLINE);
            document.add(line3);
            document.add(Chunk.NEWLINE);
            document.add(line4);
            document.add(Chunk.NEWLINE);
            document.add(line5);
            document.add(Chunk.NEWLINE);
            document.add(line6);
            document.add(Chunk.NEWLINE);
            document.add(line7);
            document.add(Chunk.NEWLINE);
            document.add(line8);
            
            // Creating a table         
            PdfPTable table = new PdfPTable(4);
            table.setWidths(new int[]{ 1, 2, 1, 1});
            table.setSpacingBefore(0f);
            table.setSpacingAfter(0f);
            table.setHorizontalAlignment(0);

            // first row
            table.addCell("Cantidad");
            table.addCell("Descripcion");
            table.addCell("Precio");
            table.addCell("Importe");
            
            table.addCell(txt_cantidad.getText());
            table.addCell(txt_descripcion.getText());
            table.addCell(txt_precio.getText());
            
            int cant = Integer.valueOf(txt_cantidad.getText());
            int pre = Integer.valueOf(txt_precio.getText());
            
            int importe = (cant * pre);
            
            String importe2 = String.valueOf(importe);
            
            table.addCell(new Phrase(importe2));
            
            PdfPTable table2 = new PdfPTable(2);
            table2.setWidths(new int[]{ 1, 1});
            table2.setWidthPercentage(30);
            table2.setSpacingBefore(0f);
            table2.setSpacingAfter(0f);
            table2.setHorizontalAlignment(0);
            
            int enviof = Integer.valueOf(txt_enviop.getText());
            int reex = Integer.valueOf(txt_reex.getText());
            
            int total = (importe+enviof+reex);
            String total2 = String.valueOf(total);
            
            // first row
            table2.addCell("ENVIO");
            table2.addCell(txt_enviop.getText());
            table2.addCell("REEX");
            table2.addCell(txt_reex.getText());
            table2.addCell("TOTAL");
            table2.addCell(new Phrase(total2));
                  
            document.add(table);
            document.add(Chunk.NEWLINE);
            document.add(table2);
         
            document.close();
            
        } catch (FileNotFoundException | DocumentException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
 
    }
}
